services:
  ollama:
    image: ollama/ollama:0.17.7
    container_name: ollama
    restart: unless-stopped
    volumes:
      - ${OLLAMA_MODELS_FOLDER}:/ollama
      - ./ollama_entrypoint.sh:/entrypoint.sh
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_HOST=0.0.0.0
    entrypoint: ["/usr/bin/bash", "/entrypoint.sh"]

  n8n:
    image: docker.n8n.io/n8nio/n8n:2.10.4
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      # For N8N
      - N8N_SECURE_COOKIE=false
      - N8N_HOST=${DOMAIN}
      # For scripts
      - PROJECT_ROOT=${PROJECT_ROOT}
      # For runners
      - N8N_RUNNERS_ENABLED=true
      - N8N_RUNNERS_MODE=external
      - N8N_RUNNERS_BROKER_LISTEN_ADDRESS=0.0.0.0
      - N8N_RUNNERS_AUTH_TOKEN=test
      - N8N_NATIVE_PYTHON_RUNNER=true
    volumes:
      - ${DATA_FOLDER}:/home/node/.n8n
      - ${KNOWLEDGE_BASE_FOLDER}:/knowledge-base
      - ${PROJECT_ROOT}/python_scripts:/python_scripts
    depends_on:
      - ollama

  task-runners:
    container_name: n8n-runners
    restart: unless-stopped
    build: .
    environment:
      - N8N_RUNNERS_TASK_BROKER_URI=http://n8n:5679
      - N8N_RUNNERS_AUTH_TOKEN=test
    depends_on:
      - n8n
